--- 
 - name: Delete build dirs onednn
   file:
          path: "{{ item }}"       
          state: absent
   with_items:
          - "/home/{{ dummyuser }}/{{ repo_name }}"

 - name: Checkout The Code From Github Using Ansible.
   git:
     repo: '{{ gitUrl }}/{{ repo_name }}.git'
     dest: /home/{{ dummyuser }}/{{ repo_name }}
 
 - name: Get the helloworld build scipt
   template:
     src: "build_helloworld.sh.j2"
     dest: "/home/{{ dummyuser }}/{{ repo_name }}/build_helloworld.sh"
     mode: '0755'

 - name: Build helloworld
   shell: ./build_helloworld.sh
   args:
      chdir: /home/{{ dummyuser }}/{{ repo_name }}


 - name: Execute helloworld
   shell: 
     cmd: ./helloWorld
     chdir: "/home/{{ dummyuser }}/{{ repo_name }}"

